CI: Trying to fix upload_docs.sh not found

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -220,41 +220,46 @@ jobs:
         with:
           fetch-depth: 0
 
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          auto-update-conda: true
-          environment-file: ci/environment_linux.yml
-          python-version: "3.10"
-          auto-activate-base: false
+      # - uses: conda-incubator/setup-miniconda@v2
+      #   with:
+      #     auto-update-conda: true
+      #     environment-file: ci/environment_linux.yml
+      #     python-version: "3.10"
+      #     auto-activate-base: false
 
-      - name: Install Dependencies
-        shell: bash -l {0}
-        run: |
-          conda install -c conda-forge nbconvert=5.6.0 mkdocs=1.3.0
-          pip install mkdocs-material==8.2.16
-          pip install 'jinja2 < 3.1'
-          pip install jupyter-client==6.1.12
+      # - name: Install Dependencies
+      #   shell: bash -l {0}
+      #   run: |
+      #     conda install -c conda-forge nbconvert=5.6.0 mkdocs=1.3.0
+      #     pip install mkdocs-material==8.2.16
+      #     pip install 'jinja2 < 3.1'
+      #     pip install jupyter-client==6.1.12
 
-      - name: Build Kernel
-        shell: bash -l {0}
-        run: |
-          ./build0.sh
-          cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_LLVM=yes -DWITH_XEUS=yes -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .
-          make
-          make install
-          ctest --output-on-failure
-          jupyter kernelspec list --json
+      # - name: Build Kernel
+      #   shell: bash -l {0}
+      #   run: |
+      #     ./build0.sh
+      #     cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_LLVM=yes -DWITH_XEUS=yes -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .
+      #     make
+      #     make install
+      #     ctest --output-on-failure
+      #     jupyter kernelspec list --json
 
       - name: Build Docs
         shell: bash -l {0}
         run: |
+          set -ex
+          pwd
+          ls
           cd doc
-          python --version
-          python convert_nb.py
-          mkdocs build
+          # python --version
+          # python convert_nb.py
+          # mkdocs build
 
       - name: Upload Docs
         shell: bash -l {0}
-        run: ./../ci/upload_docs.sh
+        run: |
+          cd doc
+          ./../ci/upload_docs.sh
         env:
           SSH_PRIVATE_KEY_DOCS: ${{ secrets.SSH_DEPLOY_KEY }}
